### ISSUE TITLE
Should not assume a fixed path for iwlist

### ISSUE THREAD

**Issue by guimier** [ancasicolica/node-wifi-scanner#1]
Because it can be anywhere in the $PATH. I have two devices (including a Raspbian “Jessie”) where it is located at `/sbin/iwlist`.

**Comment by ancasicolica** [comment]
Refactored the tool detection: instead of checking whether a tool is on the filesystem or not, it is called with a default info parameter.

Closed with V1.1, commit 530512408407e8e354efc1270f322cf6dab19665
