### ISSUE TITLE
Working on server?

### ISSUE THREAD

**Issue by gandhipranav** [ancasicolica/node-wifi-scanner#3]
Hi,

I'm new to Node so please forgive me if this is dumb.
I want to detects wifi signals around me and set up a server(Godaddy VPS) for another page to grab it.  
Earlier I used "Node-wifi" module and ran on locally and it is working. But after deployed on my godaddy VPS server it was not scan.
I would appreciate if you can spend some time looking at this. Thank you!

**Comment by ancasicolica** [comment]
Did you consider that the module only scans the WLANs of the computer where it is running? If you run it on a server, then only the WLANs detected by this machine are displayed, not the ones from a remote machine calling the script
